---
title: "First Knit"
author: "Xavier Cruz"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "Spring 2025"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer 

 I attended Desert Sands Charter High school. I graduated in November of last year. 
 I feel as though that I was always better at math then I was in English class. it was easier for me because I like problem solving more then I do writing. 
 My best subject was History and Math. Those two were always my best subjects in school.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   The Laptop that I use is a Chromebook. I feel as though I would rate myself as a 5-6 on the computer knowledge scale. My internet connection at home is very stable and works fast.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I would prefer it if my classmates called me Xavier or X for short.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  My goal in life is to be able to graduate from college and be able to find a job that pays a lot and it also something that I enjoy. The college subject that is most interesting to me is psychology. Im working towards an AA psychology for transfer then get my bachelors.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
  I actually have been to a couple of foreign countries! I had the opportunity of going to British Colombia, Canada, Paris, France and all of Italy. 
  No, I've never been in the military but if I were so get drafted I would choose to be in the Navy or in the Air Force.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I'm currently taking Math 116. I didn't know that there was a difference but it would make sense for a more complicated course to be transferable. I plan on getting an A along with my other classes. 
 






  




